# Utiliser une image de base Node.js
FROM node:16

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json dans le conteneur
COPY package*.json ./

# Installer les dépendances de l'application
RUN npm install

# Copier tous les fichiers du répertoire local dans le conteneur
COPY . .

# Exposer le port sur lequel l'application Node.js tourne (par exemple, 3000)
EXPOSE 3000

# Démarrer l'application
CMD ["node", "app.js"]
